---
".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
    - gem: ruby-pwsh
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/ci.yml:
  unmanaged: false
.github/workflows/mend.yml:
  unmanaged: false
.github/workflows/release_prep.yml:
  unmanaged: false
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
